'use client'

import { createContext, useContext, useEffect, useState } from 'react'
import type { Translations } from '@/types/translations'

type Language = 'en' | 'pt'

interface LanguageContextType {
  language: Language
  t: Translations
  toggleLanguage: () => void
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Translations> = {
  en: {
    nav: {
      home: 'Home',
      about: 'About Me',
      projects: 'Projects',
      skills: 'Skills',
      courses: 'Courses',
      publications: 'Publications',
      training: 'Training',
    },
    home: {
      name: 'Deyril M. Ibraimo',
      title: 'Agronomist & Remote Sensing Analyst',
      welcomeMessage: 'Welcome to my e-Portifolio, I am pleased to have you here!',
      rotatingTexts: [
        'Remote Sensing Analyst with over 3 years experience',
        'GIS and Earth Observation Systems profissional',
        'Agriculture, Forest and biodiversity monitoring expert',
      ],
      seeCV: 'See my CV',
      iAm: "I'm",
      downloadCV: 'Download CV',
      contact: 'Contact Me',
    },
    about: {
      title: 'About Me',
      bio: 'I\'m a Remote Sensing Analyst with over 3 years experience. My area of expertise is notably focused on GIS and Earth Observation (EO) Systems for Agriculture, Forest and biodiversity monitoring, a passion which emerged during my final year of undergraduate studies, while validating biophysical parameters in agronomic crops based on satellite imagery. It includes the collection and validation of spatial data and development of models that generate data to support decision-making in natural resource management and precision agriculture based on satellite and UAV imagery and also extends to knowledge transfer, training and empowering communities in biodiversity monitoring through participatory spatial data for community based natural resources management, measuring and analyzing biodiversity losses and adeptly measure biophysical parameters in local forests based on geospatial data. I have a passion for research design and monitoring, evaluation & Learning (MEL), which gives me a chance to be a lifelong learner through the lessons from the reality and experience of every single project.',
      professionalOverview: 'Professional Overview',
      keyHighlights: 'Key Highlights',
      highlights: {
        specialized: 'Specialized in GIS and Earth Observation Systems',
        passionate: 'Passionate about research design and MEL',
        community: 'Community engagement and knowledge transfer expert',
      },
      quote: 'Every project is an opportunity to learn and grow, transforming data into actionable insights for sustainable development.',
      expertiseAreas: {
        remoteSensing: {
          title: 'Remote Sensing & GIS',
          description: 'Expert in satellite imagery analysis, Earth Observation systems, and geospatial data processing for environmental monitoring.',
        },
        agricultureForest: {
          title: 'Agriculture & Forest Monitoring',
          description: 'Specialized in biophysical parameter validation, crop monitoring, and forest biodiversity assessment using EO data.',
        },
        spatialData: {
          title: 'Spatial Data Management',
          description: 'Proficient in collecting, validating, and developing models from spatial data to support decision-making processes.',
        },
        communityEngagement: {
          title: 'Community Engagement',
          description: 'Experienced in participatory spatial data collection and empowering communities in natural resource management.',
        },
        mel: {
          title: 'Monitoring & Evaluation',
          description: 'Passionate about research design, MEL frameworks, and transforming project experiences into learning opportunities.',
        },
        researchDesign: {
          title: 'Research Design',
          description: 'Skilled in designing research methodologies that combine quantitative and qualitative approaches for comprehensive analysis.',
        },
      },
    },
    projects: {
      title: 'My Projects',
      viewDetails: 'View Details',
      date: 'Date',
      description: 'Description',
      space4all: {
        title: 'SPACE4ALL',
        subtitle: 'Mapping climate vulnerabilities of slums by combining citizen science and earth observation technology',
        date: '2024 - ongoing',
        overview: 'SPACE4ALL is a project owned by the ITC- University of Twente and NWO (Dutch Research Council) that aims to unravel the climate vulnerability of slum communities in large and secondary cities by combining Citizen Science and Earth Observation methods. Earth Observation methods have the advantage of producing physical data for large areas and have shown their capability to map the physical aspects of slums. The project addresses the gaps by developing an innovative AI methodology by combining Citizen Science data and Earth Observation data with climate change data to locate hotspots of urban poor exposed to climate-related hazards (e.g., sea-level rise, storms, floods, extreme temperatures).',
      },
      bazaruto: {
        title: 'Participatory Coastal Resources Mapping in Greater Bazaruto Key Biodiversity Area',
        subtitle: 'Participatory Coastal Resources Mapping in Greater Bazaruto Key Biodiversity Area',
        date: 'Oct. 2023 - Apr. 2024',
        overviewText: 'The Greater Bazaruto KBA houses diverse marine ecosystems and because of its abundant biodiversity and diverse landscapes, this area holds significant ecological, economic, and societal importance, with tourism and fisheries serving as primary activities. This unique ecosystem sustains the livelihoods of local communities residing within the BANP and coastal communities in the mainland districts of Vilankulos, Inhassoro, and Govuro. However, the habitats and species face threats from illegal and unsustainable fishing practices, unregulated natural resource utilization.',
      },
      luisa: {
        title: 'Land Use Intensity\'s Potential, Vulnerability and Resilience for Sustainable Agriculture in Africa (LUISA)',
        subtitle: 'Land Use Intensity\'s Potential, Vulnerability and Resilience for Sustainable Agriculture in Africa (LUISA)',
        date: '2024 - Oct. 2025',
        overviewText: 'The long-term goal of "Land Use Intensity\'s Potential, Vulnerability and Resilience for Sustainable Agriculture in Africa" (LUISA) is to build the resilience of smallholder farmers and pastoralists in Africa to land use intensification resulting from rapid population growth and climate change. LUISA will achieve this goal by developing a satellite-driven decision-support platform from which policymakers can deliver more effective and reliable carbon monitoring across Africa. Human Appropriation of Net Primary Productivity (HANPP) is a key environmental indicator that helps decision-makers to understand the drivers and consequences of land use intensification on carbon dynamics on a pixel basis over large areas.',
      },
      fisheriesBazaruto: {
        title: 'Fisheries Value Chain Mapping and Community Governance in Bazaruto Archipelago National Park',
        subtitle: 'Fisheries Value Chain Mapping and Community Governance in Bazaruto Archipelago National Park',
        date: '2023 - 2024',
        overview: 'Overview',
        overviewText: 'The fisheries value chain mapping and governance assessment aims at understanding the effects of the fisheries activities across the region, including the influence of community governance structures as the mechanisms for a participatory marine resources management.',
        objective: 'The project seeks to deliver a comprehensive and community-informed assessment of the fisheries value chain in and around the Bazaruto Archipelago National Park. The overall objective was to generate evidence to inform more sustainable and inclusive fisheries management while supporting the socio-economic well-being of local communities. Recognizing the central role of fisheries as the primary economic activity in the region, the project adopted a nuanced mapping approach that captured the micro-dynamics of the value chain at the community level.',
        methodology: 'This involved extensive sampling and site visits to all communities within and around BANP, enabling a detailed understanding of localized practices, key actors, and interactions across the fishing economy. The assessment also examined the multi-scalar dimensions of the fisheries value chain, acknowledging that fish products from the BANP region are not only consumed locally but also transported to major urban markets such as Maputo, Beira, and Chimoio. As such, the study incorporated both local and national-level actors to provide a comprehensive picture of how fish commodities move across regions and supply systems.',
        results: 'Additionally, 17 community committees were created throughout the archipelago as a way to strengthen community management of natural resources. The committees were legalized and trained so that they can actively participate in decision-making processes that influence the daily lives of the communities.',
        appliedSkills: 'Applied skills',
        institutions: 'Involved institutions',
        skills: {
          biodiversityConservation: 'Biodiversity Conservation',
          dataAnalysis: 'Data Analysis',
          quantitativeResearch: 'Quantitative Research',
          qualitativeResearch: 'Qualitative Research',
          communityEngagement: 'Community Engagement',
          naturalResourcesManagement: 'Natural Resources Management',
        },
      },
      communityLedNRM: {
        title: 'Community-Led Natural Resources Management through Participatory Spatial Data',
        subtitle: 'Empowering Communities in the Gorongosa-Marromeu Complex for Sustainable Resource Management',
        date: 'Aug 2024 - Apr 2025',
        overview: 'Overview',
        overviewText: 'This project, funded by USAID, arises from the observation of the fact that the communities in Mozambique, particularly in the central province of Sofala, serve as custodians of natural resources. Beyond their constitutional rights, these communities are entrusted with the following responsibilities: i) Protection and Conservation, II) Sustainability and iii) Livelihood improvement.',
        objective: 'Carried out in collaboration with Gorongosa National Park and the respective district government, the project aimed to empower local communities in natural resources management through participatory spatial data techniques, including: Enhancing Community Engagement in the Wildlife Crime, through active participation of community members, particularly youth and women in the decision-making processes related to natural resource management and establish an inclusive framework that actively involves community members in resource management decision-making by leveraging data collected by the communities.',
        methodology: 'The execution of the project was guided through the following activities: community mobilization and engagement, promotion of community capacity building and training sessions on community based natural resources management, participatory spatial mapping, data collection using mobile devices, identification and reporting of wildlife crime, and value chain mapping and opportunities.',
        results: '25 members of local natural resource management committees are now able to use mobile devices to collect evidence and report environmental crimes in near real-time through a spatial data-based system, reinforcing their surveillance capabilities against environmental crimes at the community level. 5 communities from Gorongosa National Park buffer zone have been provided with knowledge about identifying alternative livelihoods and trained in biodiversity conservation and the sustainable use of natural resources.',
        appliedSkills: 'Applied skills',
        institutions: 'Involved institutions',
        skills: {
          mel: 'Monitoring, Evaluation & Learning',
          sustainableLivelihood: 'Sustainable Livelihoods',
          gis: 'GIS',
          naturalResourcesManagement: 'Natural Resources Management',
        },
      },
    },
    skills: {
      title: 'My Skills',
      tools: 'Tools',
      remoteSensing: 'Remote Sensing',
      remoteSensingDescription: 'Expert in satellite imagery analysis, Earth Observation systems, and geospatial data processing for environmental monitoring.',
      gis: 'Geographic Information Systems (GIS)',
      gisDescription: 'Proficient in spatial data collection, analysis, and visualization using advanced GIS tools for mapping and decision-making.',
      dataAnalysis: 'Data Analysis',
      dataAnalysisDescription: 'Skilled in statistical analysis, data modeling, and interpretation of complex datasets to support research and decision-making processes.',
      precisionAgriculture: 'Precision Agriculture',
      precisionAgricultureDescription: 'Specialized in biophysical parameter validation, crop monitoring, and agricultural resource management using EO data and UAV technology.',
      dataManagement: 'Data Management',
      dataManagementDescription: 'Experienced in database design, data validation, and developing models that generate actionable insights for natural resource management.',
      mel: 'Monitoring, Evaluation & Learning (MEL)',
      melDescription: 'Passionate about research design, MEL frameworks, and transforming project experiences into learning opportunities for continuous improvement.',
      quantitativeQualitative: 'Quantitative and Qualitative Research',
      quantitativeQualitativeDescription: 'Skilled in designing research methodologies that combine quantitative and qualitative approaches for comprehensive analysis.',
      naturalResourcesManagement: 'Natural Resources Management',
      naturalResourcesManagementDescription: 'Experienced in measuring and analyzing biodiversity, forest monitoring, and supporting sustainable natural resource management decisions.',
      sustainableLivelihood: 'Sustainable Livelihood',
      sustainableLivelihoodDescription: 'Committed to developing solutions that support sustainable livelihoods and community resilience through data-driven approaches.',
      communityEngagement: 'Community Engagement',
      communityEngagementDescription: 'Experienced in participatory spatial data collection and empowering communities in natural resource management through knowledge transfer.',
    },
    courses: {
      title: 'Courses',
      coursesList: {
        bscAgriculturalEngineering: 'BSc. Agricultural Engineering',
        uavPrecisionAgriculture: 'UAV in Precision Agriculture',
        advancedStatistics: 'Advanced Statistics and Experimental Design',
        qualiQuantitativeResearch: 'Quali and Quantitative Research & Data Analysis',
      },
      institutions: {
        eduardoMondlaneUniversity: 'Eduardo Mondlane University',
        universityOfTwente: 'University of Twente',
        centreOfExcellenceUEM: 'Centre of Excellence of Agrifood systems and Nutrition of UEM',
        amazonasUniversity: 'Amazonas University',
      },
      locations: {
        mozambique: 'Mozambique',
        netherlands: 'Netherlands',
        brazil: 'Brazil',
      },
    },
    publications: {
      title: 'Publications',
      readMore: 'Read More',
      publicationsList: {
        exposedUnmapped: 'Exposed yet unmapped? Evidence of differential flood exposure in deprived urban areas using citizen science',
        validationLeafArea: 'Validation of Leaf Area Index and Canopy Water Content through Sentinel-2 images in maize (Zea Mays L.) crop: Case study of Vilankulo district',
      },
      authors: {
        oliveiraEtAl: 'Oliveira, L; Campomanes, E; Dijkstra, A; Belgiu, M; Adiku, P; Wanjiru, N; Lizian Onyango, L; Ibraimo, D; Flor, R; Van Den Bout, B; Zevenbergen, J & Kuffer, M',
        ibraimoMananze: 'Ibraimo, D.M. & Mananze, S.E.',
      },
      journals: {
        researchSquare: 'Research Square (Preprint)',
        scienceCribe: 'ScienceCribe',
      },
    },
    training: {
      title: 'Training & Skills Transfers',
      educationQuote: 'Education is the most powerful weapon you can use to change the world',
      educationQuoteAuthor: 'Nelson Mandela',
      educationStatement: 'Moved by the quote above, I use part of my time to share and/or transfer skills to the youth and the upcoming generations.',
      koboToolbox: {
        title: 'Kobo ToolBox for Data Collection and Data Management',
        date: 'November 2025',
        description: 'This training was provided to final-year students from Pungue University by Mozambique Flying Labs, as part of our mission of inclusive digital transformation in the country. The students were provided with material on principles of quantitative research, data collection through mobile devices, and data management. The two-day training consisted of theoretical and practical components, allowing students to improve in a realistic field context of data collection.',
        students: '25 students',
        providedBy: 'Mozambique Flying Labs',
        programs: 'Programs covered:',
        programsList: 'Biological Sciences, Agronomy, Renewable Energies Engineering, Physics and Applied Mathematics',
        outcome: 'The training enriched the students\' hard skills to improve the quality of their academic research, as well as technological skills that make them competitive in the labour market.',
      },
      googleEarthEngine: {
        title: 'Google Earth Engine Webinar',
        date: 'August 2025',
        description: 'In this public webinar organized by Mozambique Flying Labs, our objective was to demonstrate in practice how data from Earth observation systems can be used for informed decision-making in various sectors through datasets available on this powerful remote sensing platform.',
        attendees: '125 attendees',
        providedBy: 'Mozambique Flying Labs',
        examples: 'Practical examples included:',
        examplesList: 'Agricultural monitoring, disaster management, and deforestation monitoring.',
        participants: 'The webinar had 125 people attending, including students, public and private sector employees, as well as representatives from NGOs and community-based associations.',
      },
      googleMyMaps: {
        title: 'Google My Maps For Flood Mapping',
        date: 'February 2025',
        description: 'The Google My Maps training for mapping flooded areas was part of the Space4ALL project, which aimed to empower members of local communities in flood-prone neighborhoods in the cities of Beira and Chimoio in Mozambique and Kisumu in Kenya. This training aimed to empower community members to generate and share data on floods, as well as a history of critical locations in their neighborhoods, enabling the reception of detailed information on flood history in these intervention areas of the Space4ALL project and validating the flood early warning model.',
        providedBy: 'University of Twente & Data4MOZ',
        locations: 'Training locations:',
        locationsList: 'The training was offered by teams from the Faculty of Geoinformation Sciences at the University of Twente and Data4MOZ to the communities of Nyalenda B and Manyata B in Kenya and 25 de Setembro, Centro Hípico, Munhava and Ponta-Gea in Mozambique.',
      },
      sustainableNRM: {
        title: 'Sustainable Natural Resources Management',
        date: '2024',
        description: 'This training was provided to 5 communities Gorongosa National buffer zone, Park as part of the community-led natural resources management through participatory spatial data project conducted by Data4MOZ and funded by USAID.',
        communities: '5 communities',
        providedBy: 'Data4MOZ & USAID',
        communitiesList: 'Communities: Catemo, Nhabawa, Chidanga, Maciamboza and Muanandimae',
        outcomes: 'This training made it possible to raise awareness among members of the Catemo, Nhabawa, Chidanga, Maciamboza and Muanandimae communities about the sustainable use of natural resources and the identification of alternative livelihoods to alleviate pressure on natural resources, such as beekeeping, organic farming, etc., and to reduce poaching and illegal logging of timber species.',
      },
      communityGovernance: {
        title: 'Community Governance',
        date: '2024',
        description: 'The training in community governance was aimed at 17 newly established community committees by Data4MOZ in the Bazaruto Archipelago National Park (BANP), with the goal of improving community participation and involvement when it comes to establishing norms that impact the lives of the communities residing in the archipelago.',
        committees: '17 committees',
        providedBy: 'Data4MOZ',
        contentTitle: 'Training content:',
        content: 'The training consisted of principles of operation for community committees, awareness of aquatic and terrestrial biodiversity conservation, as well as the management plan in force in BANP.',
      },
    },
    contact: {
      title: 'Contact Me',
      sendMessage: 'Send Message',
      nome: 'First Name',
      nomePlaceholder: 'Enter your first name',
      apelido: 'Last Name',
      apelidoPlaceholder: 'Enter your last name',
      email: 'Email',
      emailPlaceholder: 'your.email@example.com',
      assunto: 'Subject',
      assuntoPlaceholder: 'What is this about?',
      contacto: 'Phone',
      contactoPlaceholder: '+258 845 486 656',
      mensagem: 'Message',
      mensagemPlaceholder: 'Write your message here...',
      send: 'Send Message',
      sending: 'Sending...',
      success: 'Sent!',
      successMessage: 'Message sent successfully! We will contact you soon.',
      errorMessage: 'Error sending message. Please try again later.',
      connectWithUs: 'Connect with Us',
      scheduleConsultation: 'Schedule a consultation or send us a message',
      whatsappMessage: 'Hello! I would like to get in touch.',
      followUs: 'Follow Us',
      location: 'Location',
      country: 'Mozambique',
      province: 'Manica Province',
      city: 'Chimoio',
    },
    footer: {
      allRightsReserved: 'All rights reserved',
    },
    chatbot: {
      openChatbot: 'Open chatbot',
      closeChatbot: 'Close chatbot',
      title: 'Ask about Deyril',
      online: 'Online',
      placeholder: 'Type your question...',
      hint: 'Ask about experience, skills, projects, education, or contact info',
      greeting: "Hello! I'm here to answer questions about Deyril Marlon Ibraimo. What would you like to know?",
      defaultResponse: "I can help you learn about Deyril Marlon Ibraimo's experience, skills, projects, education, publications, and contact information. What would you like to know?",
      typing: 'Typing...',
    },
    stats: {
      title: 'Achievements & Impact',
      yearsExperience: 'Years of Experience',
      projectsCompleted: 'Projects Completed',
      publications: 'Publications',
      communitiesTrained: 'Communities Trained',
      countriesWorked: 'Countries Worked',
    },
    timeline: {
      title: 'Professional Timeline',
      subtitle: 'A journey through my professional experience, education, and key achievements',
      items: [
        {
          type: 'work',
          typeLabel: 'Work Experience',
          title: 'Operations Coordinator',
          period: 'Apr 2024 - Current',
          organization: 'Data4MOZ, SA',
          location: 'Mozambique',
          description: 'Leading operations and coordinating multiple research projects focused on climate vulnerability assessment, land use monitoring, and community engagement across African countries.',
          highlights: [
            'Mapping climate vulnerabilities of deprived areas by combining citizen science and Earth observation technology in Kisumu (Kenya), Beira and Chimoio (Mozambique) through Space4ALL research program',
            'Monitoring changes in land use and cover: identification of areas of pressure on natural ecosystems',
            'Assessment of sustainability of land use in agricultural practices in the Beira corridor',
            'Mapping Wildlife Crimes hotspots in Gorongosa National Park Buffer Zone',
            'Conducting community training for Wildlife crimes tracking using Spatial Data tools',
            'Mapping Agricultural areas through Sentinel-2 imagery and crop database management',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Work Experience',
          title: 'Operations Coordinator',
          period: 'Current',
          organization: 'Mozambique Flying Labs',
          location: 'Mozambique',
          description: 'Coordinating STEM promotion activities and developing strategies for adopting UAV technology, data science, and artificial intelligence for sustainable development in Southern Africa.',
          highlights: [
            'Coordination of STEM (Science, Technology, Engineering, and Mathematics) promotion activities in Mozambican communities',
            'Development of strategies for adopting Unmanned Aerial Vehicle (UAV) technology',
            'Promoting data science and artificial intelligence for sustainable development',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Work Experience',
          title: 'Remote Sensing Analyst',
          period: '2023 - 2024',
          organization: 'Data4MOZ, SA',
          location: 'Mozambique',
          description: 'Conducting participatory coastal resources mapping, artisanal fishing value chain mapping, and developing remote sensing-driven monitoring frameworks for land cover and biomass estimation.',
          highlights: [
            'Participatory coastal resources mapping and Artisanal Fishing Value Chain Mapping in Greater Bazaruto Key Biodiversity Area (KBA)',
            'Development of remote sensing-driven HANPP monitoring framework for general land cover types (agricultural, forest, grassland, urban)',
            'Estimating Biomass losses in African countries: Mozambique, Senegal, Uganda and Ethiopia through LUISA project',
            'Monitoring Maize, Rice and Soybean cropland based on Satellite imagery in center region of Mozambique',
            'Identification of inefficient agricultural plots',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Work Experience',
          title: 'Agricultural Entomology Trainer',
          period: 'Nov - Dec 2023',
          organization: 'Instituto Superior Dom Bosco',
          location: 'Mozambique',
          description: 'Conducting training in integrated agricultural pest management, identification, monitoring and training of agricultural pests.',
          highlights: [
            'Conducting training in integrated agricultural pest management',
            'Identification, monitoring and training of agricultural pests',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Work Experience',
          title: 'Field Enumerator',
          period: 'Apr - Jun 2023',
          organization: 'Data4MOZ, SA',
          location: 'Mozambique',
          description: 'Leading geospatial data collection for socioeconomic surveys, data cleaning and report writing, and team management.',
          highlights: [
            'Leadership on Geospatial data collection for socioeconomic surveys',
            'Data cleaning and report writing',
            'Team management',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Work Experience',
          title: 'Geographic Information Technology Monitor Lecturer',
          period: 'Jul - Dec 2022',
          organization: 'Instituto Superior Dom Bosco',
          location: 'Mozambique',
          description: 'Teaching Geographic Information Technology and conducting assessment of Land-Based Investment in Mozambique in partnership with SNV.',
          highlights: [
            'Teaching Geographic Information Technology',
            'Assessment of Land-Based Investment in Mozambique in partnership with SNV',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Work Experience',
          title: 'Field Technician in Research Program',
          period: 'Aug - Dec 2022',
          organization: 'Centre of Excellence in Agri-food systems and Nutrition',
          location: 'Mozambique',
          description: 'Working on food security, agribusiness and resource use efficiency in agriculture based on Earth Observation system.',
          highlights: [
            'Remote sensing-based data collection, processing and insights development for decision making in sustainable agriculture',
            'Project: Food security, agribusiness and resource use efficiency in agriculture based on Earth Observation system',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Work Experience',
          title: 'Research Assistant',
          period: '2022',
          organization: 'Eduardo Mondlane University',
          location: 'Mozambique',
          description: 'Geospatial data acquisition and processing, remote sensing applied to precision agriculture.',
          highlights: [
            'Geospatial data acquisition (Copernicus and USGS database) and vector data processing',
            'Remote Sensing applied to precision agriculture - Mapping and monitoring agricultural areas based on Sentinel-2 images using SNAP',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Work Experience',
          title: 'Genetics and Plant Breeding Monitor Lecturer',
          period: 'Sep 2021 - Jun 2022',
          organization: 'Eduardo Mondlane University',
          location: 'Mozambique',
          description: 'Supervision of field activities in genetic plants breeding, autogamous and allogamous plants breeding, and plants biotechnology.',
          highlights: [
            'Supervision of field activities in genetic plants breeding',
            'Autogamous and Allogamous plants breeding',
            'Plants biotechnology',
          ],
        },
        {
          type: 'education',
          typeLabel: 'Education',
          title: 'BSc. Degree in Agronomy',
          period: '2019 - 2023',
          organization: 'Eduardo Mondlane University (UEM)',
          location: 'Mozambique',
          description: 'Bachelor of Science in Agronomy with specialization in remote sensing applications for agriculture and crop monitoring.',
        },
        {
          type: 'education',
          typeLabel: 'Education',
          title: 'SNE General High School - Sciences & Biology',
          period: '2014 - 2018',
          organization: 'Magude Secondary School',
          location: 'Mozambique',
          description: 'High school education with focus on Sciences and Biology.',
        },
        {
          type: 'achievement',
          typeLabel: 'Certificate',
          title: 'UAVs in Precision Agriculture',
          period: '2024',
          organization: 'Faculty of Geo-Information and Earth Observation of University of Twente',
          location: 'Netherlands',
          description: 'Certificate in UAV applications for precision agriculture and remote sensing.',
        },
        {
          type: 'achievement',
          typeLabel: 'Certificate',
          title: 'Advanced Statistics and Experimental Design',
          period: '2023',
          organization: 'Eduardo Mondlane University',
          location: 'Mozambique',
          description: 'Certificate in advanced statistics and experimental design for agricultural research.',
        },
        {
          type: 'achievement',
          typeLabel: 'Certificate',
          title: 'Qualitative and Quantitative Research and Data Analysis',
          period: '2023',
          organization: 'State University of Amazonas',
          location: 'Brazil',
          description: 'Certificate in qualitative and quantitative research methods and data analysis.',
        },
      ],
    },
    space4all: {
      title: 'SPACE4ALL',
      subtitle: 'Mapping climate vulnerabilities of slums by combining citizen science and earth observation technology',
      period: '2024 - ongoing',
      overview: 'Overview',
      overviewText: 'SPACE4ALL is a project owned by the ITC- University of Twente and NWO (Dutch Research Council) that aims to unravel the climate vulnerability of slum communities in large and secondary cities by combining Citizen Science and Earth Observation methods. Earth Observation methods have the advantage of producing physical data for large areas and have shown their capability to map the physical aspects of slums. The project addresses the gaps by developing an innovative AI methodology by combining Citizen Science data and Earth Observation data with climate change data to locate hotspots of urban poor exposed to climate-related hazards (e.g., sea-level rise, storms, floods, extreme temperatures).',
      approach: 'This novel approach had the main purpose the development and training of deep learning models in order to map the degree of vulnerability of slum communities to climate-related risks across both large and secondary cities in Africa, to enhance the precision and the flooding early-warning capacity of the model.',
      locations: 'The project was conducted in African cities, namely Kisumu and Nairobi in Kenya, Accra and Tema in Ghana and at last Beira and Chimoio in Mozambique, in partnership with African institutions such as Data4MOZ and Sdi Kenya.',
      methodology: 'The study was conducted in a participatory format where the citizens were able to point and map the vulnerable areas of the city to climate hazards, especially flooding, including its depth level of the floods for the latest events.',
      contribution: 'Contribution',
      contributionText: 'Under the Data4MOZ umbrella, as remote sensing analyst in the institution, my role for Space4All went from the field data collect and model validation, conducting field validation sessions in Kisumo (Kenya) together with ITC-University of Twente members and leading the activities in Beira and Chimoio (Mozambique), engaging the local communities and stakeholders for model validation sessions and gather subsidies by field observations, transect walks and mapping informal settlements.',
      institutions: 'Involved institutions',
      furtherInfo: 'For further information',
      contact: 'Lorraine Trento Oliveira (ITC-UT Space4all Researcher)',
    },
  },
  pt: {
    nav: {
      home: 'Início',
      about: 'Sobre Mim',
      projects: 'Projetos',
      skills: 'Competências',
      courses: 'Cursos',
      publications: 'Publicações',
      training: 'Formação',
    },
    home: {
      name: 'Deyril M. Ibraimo',
      title: 'Agrónomo e Analista de Sensoriamento Remoto',
      welcomeMessage: 'Bem-vindo ao meu e-Portfólio, é um prazer tê-lo aqui!',
      rotatingTexts: [
        'Analista de Sensoriamento Remoto com mais de 3 anos de experiência',
        'Especialista em Sistemas de SIG e Observação da Terra',
        'Especialista em monitoramento de Agricultura, Floresta e biodiversidade',
      ],
      seeCV: 'Ver meu CV',
      iAm: 'Sou',
      downloadCV: 'Baixar CV',
      contact: 'Entre em Contato',
    },
    about: {
      title: 'Sobre Mim',
      bio: 'Sou um Analista de Sensoriamento Remoto com mais de 3 anos de experiência. A minha área de especialização está focada em Sistemas de SIG e Observação da Terra (EO) para Agricultura, Floresta e monitoramento de biodiversidade, uma paixão que surgiu durante o meu último ano de estudos de graduação, enquanto validava parâmetros biofísicos em culturas agronômicas com base em imagens de satélite. Inclui a recolha e validação de dados espaciais e desenvolvimento de modelos que geram dados para apoiar a tomada de decisões na gestão de recursos naturais e agricultura de precisão com base em imagens de satélite e UAV e também se estende à transferência de conhecimento, formação e capacitação de comunidades no monitoramento da biodiversidade através de dados espaciais participativos para gestão comunitária de recursos naturais, medindo e analisando perdas de biodiversidade e medindo habilmente parâmetros biofísicos em florestas locais com base em dados geoespaciais. Tenho uma paixão pelo design de pesquisa e monitoramento, avaliação e aprendizagem (MEL), o que me dá a oportunidade de ser um aprendiz ao longo da vida através das lições da realidade e experiência de cada projeto.',
      professionalOverview: 'Visão Profissional',
      keyHighlights: 'Destaques Principais',
      highlights: {
        specialized: 'Especializado em Sistemas de SIG e Observação da Terra',
        passionate: 'Apaixonado por design de pesquisa e MEL',
        community: 'Especialista em engajamento comunitário e transferência de conhecimento',
      },
      quote: 'Cada projeto é uma oportunidade de aprender e crescer, transformando dados em insights acionáveis para o desenvolvimento sustentável.',
      expertiseAreas: {
        remoteSensing: {
          title: 'Sensoriamento Remoto & SIG',
          description: 'Especialista em análise de imagens de satélite, sistemas de Observação da Terra e processamento de dados geoespaciais para monitoramento ambiental.',
        },
        agricultureForest: {
          title: 'Monitoramento de Agricultura & Floresta',
          description: 'Especializado em validação de parâmetros biofísicos, monitoramento de culturas e avaliação de biodiversidade florestal usando dados de EO.',
        },
        spatialData: {
          title: 'Gestão de Dados Espaciais',
          description: 'Proficiente na recolha, validação e desenvolvimento de modelos a partir de dados espaciais para apoiar processos de tomada de decisão.',
        },
        communityEngagement: {
          title: 'Engajamento Comunitário',
          description: 'Experiente em coleta participativa de dados espaciais e capacitação de comunidades na gestão de recursos naturais.',
        },
        mel: {
          title: 'Monitoramento & Avaliação',
          description: 'Apaixonado por design de pesquisa, estruturas MEL e transformação de experiências de projeto em oportunidades de aprendizagem.',
        },
        researchDesign: {
          title: 'Design de Pesquisa',
          description: 'Habilidoso em projetar metodologias de pesquisa que combinam abordagens quantitativas e qualitativas para análise abrangente.',
        },
      },
    },
    projects: {
      title: 'Meus Projetos',
      viewDetails: 'Ver Detalhes',
      date: 'Data',
      description: 'Descrição',
      space4all: {
        title: 'SPACE4ALL',
        subtitle: 'Mapeamento de vulnerabilidades climáticas de favelas combinando ciência cidadã e tecnologia de observação da terra',
        date: '2024 - em curso',
        overview: 'SPACE4ALL é um projeto da ITC- University of Twente e NWO (Conselho Holandês de Pesquisa) que visa desvendar a vulnerabilidade climática de comunidades de favelas em grandes e cidades secundárias combinando métodos de Ciência Cidadã e Observação da Terra. Os métodos de Observação da Terra têm a vantagem de produzir dados físicos para grandes áreas e mostraram sua capacidade de mapear os aspectos físicos das favelas. O projeto aborda as lacunas desenvolvendo uma metodologia inovadora de IA combinando dados de Ciência Cidadã e dados de Observação da Terra com dados de mudanças climáticas para localizar pontos críticos de pobres urbanos expostos a perigos relacionados ao clima (por exemplo, aumento do nível do mar, tempestades, inundações, temperaturas extremas).',
      },
      bazaruto: {
        title: 'Mapeamento Participativo de Recursos Costeiros na Grande Área de Biodiversidade Chave de Bazaruto',
        subtitle: 'Mapeamento Participativo de Recursos Costeiros na Grande Área de Biodiversidade Chave de Bazaruto',
        date: 'Out. 2023 - Abr. 2024',
        overviewText: 'A Grande Área de Biodiversidade Chave (KBA) de Bazaruto abriga diversos ecossistemas marinhos e, devido à sua abundante biodiversidade e paisagens diversas, esta área possui importância ecológica, económica e social significativa, com o turismo e a pesca servindo como atividades primárias. Este ecossistema único sustenta os meios de subsistência das comunidades locais que residem dentro do BANP e das comunidades costeiras nos distritos continentais de Vilankulos, Inhassoro e Govuro. No entanto, os habitats e espécies enfrentam ameaças de práticas de pesca ilegais e insustentáveis, utilização não regulamentada de recursos naturais.',
      },
      luisa: {
        title: 'Potencial, Vulnerabilidade e Resiliência da Intensidade do Uso da Terra para Agricultura Sustentável em África (LUISA)',
        subtitle: 'Potencial, Vulnerabilidade e Resiliência da Intensidade do Uso da Terra para Agricultura Sustentável em África (LUISA)',
        date: '2024 - Out. 2025',
        overviewText: 'O objetivo de longo prazo do "Potencial, Vulnerabilidade e Resiliência da Intensidade do Uso da Terra para Agricultura Sustentável em África" (LUISA) é construir a resiliência de pequenos agricultores e pastores em África à intensificação do uso da terra resultante do rápido crescimento populacional e mudanças climáticas. O LUISA alcançará este objetivo desenvolvendo uma plataforma de apoio à decisão baseada em satélites a partir da qual os formuladores de políticas podem fornecer monitorização de carbono mais eficaz e confiável em toda a África. A Apropriação Humana da Produtividade Primária Líquida (HANPP) é um indicador ambiental chave que ajuda os decisores a compreender os impulsionadores e consequências da intensificação do uso da terra na dinâmica do carbono numa base de pixel sobre grandes áreas.',
      },
      fisheriesBazaruto: {
        title: 'Mapeamento da Cadeia de Valor da Pesca e Governança Comunitária no Parque Nacional do Arquipélago de Bazaruto',
        subtitle: 'Mapeamento da Cadeia de Valor da Pesca e Governança Comunitária no Parque Nacional do Arquipélago de Bazaruto',
        date: '2023 - 2024',
        overview: 'Visão Geral',
        overviewText: 'O mapeamento da cadeia de valor da pesca e a avaliação da governança visam compreender os efeitos das atividades pesqueiras em toda a região, incluindo a influência das estruturas de governança comunitária como mecanismos para uma gestão participativa dos recursos marinhos.',
        objective: 'O projeto procura fornecer uma avaliação abrangente e informada pela comunidade da cadeia de valor da pesca dentro e ao redor do Parque Nacional do Arquipélago de Bazaruto. O objetivo geral foi gerar evidências para informar uma gestão pesqueira mais sustentável e inclusiva, apoiando o bem-estar socioeconómico das comunidades locais. Reconhecendo o papel central da pesca como atividade económica primária na região, o projeto adotou uma abordagem de mapeamento que capturou as micro-dinâmicas da cadeia de valor ao nível comunitário.',
        methodology: 'Isso envolveu amostragem extensiva e visitas a todas as comunidades dentro e ao redor do BANP, permitindo uma compreensão detalhada das práticas localizadas, atores-chave e interações na economia pesqueira. A avaliação também examinou as dimensões multi-escalares da cadeia de valor da pesca, reconhecendo que os produtos pesqueiros da região do BANP não são apenas consumidos localmente, mas também transportados para grandes mercados urbanos como Maputo, Beira e Chimoio. Como tal, o estudo incorporou atores locais e nacionais para fornecer uma imagem abrangente de como as commodities pesqueiras se movem entre regiões e sistemas de abastecimento.',
        results: 'Além disso, 17 comités comunitários foram criados em todo o arquipélago como forma de fortalecer a gestão comunitária dos recursos naturais. Os comités foram legalizados e treinados para que possam participar ativamente nos processos de tomada de decisão que influenciam a vida quotidiana das comunidades.',
        appliedSkills: 'Habilidades aplicadas',
        institutions: 'Instituições envolvidas',
        skills: {
          biodiversityConservation: 'Conservação da Biodiversidade',
          dataAnalysis: 'Análise de Dados',
          quantitativeResearch: 'Investigação Quantitativa',
          qualitativeResearch: 'Investigação Qualitativa',
          communityEngagement: 'Engajamento Comunitário',
          naturalResourcesManagement: 'Gestão de Recursos Naturais',
        },
      },
      communityLedNRM: {
        title: 'Gestão Comunitária de Recursos Naturais através de Dados Espaciais Participativos',
        subtitle: 'Capacitação de Comunidades no Complexo Gorongosa-Marromeu para Gestão Sustentável de Recursos',
        date: 'Ago 2024 - Abr 2025',
        overview: 'Visão Geral',
        overviewText: 'Este projeto, financiado pela USAID, surge da observação do fato de que as comunidades em Moçambique, particularmente na província central de Sofala, servem como guardiãs dos recursos naturais. Além dos seus direitos constitucionais, essas comunidades são incumbidas das seguintes responsabilidades: i) Proteção e Conservação, II) Sustentabilidade e iii) Melhoria dos meios de subsistência.',
        objective: 'Realizado em colaboração com o Parque Nacional da Gorongosa e o governo distrital respectivo, o projeto visou capacitar as comunidades locais na gestão de recursos naturais através de técnicas de dados espaciais participativos, incluindo: Melhorar o Engajamento Comunitário no Crime contra a Vida Selvagem, através da participação ativa dos membros da comunidade, particularmente jovens e mulheres nos processos de tomada de decisão relacionados à gestão de recursos naturais e estabelecer uma estrutura inclusiva que envolva ativamente os membros da comunidade na tomada de decisões de gestão de recursos, aproveitando os dados coletados pelas comunidades.',
        methodology: 'A execução do projeto foi guiada através das seguintes atividades: mobilização e engajamento comunitário, promoção de capacitação comunitária e sessões de treinamento sobre gestão comunitária de recursos naturais, mapeamento espacial participativo, coleta de dados usando dispositivos móveis, identificação e relato de crimes contra a vida selvagem, e mapeamento da cadeia de valor e oportunidades.',
        results: '25 membros dos comités locais de gestão de recursos naturais agora são capazes de usar dispositivos móveis para coletar evidências e relatar crimes ambientais quase em tempo real através de um sistema baseado em dados espaciais, reforçando suas capacidades de vigilância contra crimes ambientais ao nível comunitário. 5 comunidades da zona tampão do Parque Nacional da Gorongosa receberam conhecimento sobre identificação de meios de subsistência alternativos e foram treinadas em conservação da biodiversidade e uso sustentável dos recursos naturais.',
        appliedSkills: 'Habilidades aplicadas',
        institutions: 'Instituições envolvidas',
        skills: {
          mel: 'Monitoramento, Avaliação e Aprendizagem',
          sustainableLivelihood: 'Meios de Subsistência Sustentáveis',
          gis: 'SIG',
          naturalResourcesManagement: 'Gestão de Recursos Naturais',
        },
      },
    },
    skills: {
      title: 'Minhas Competências',
      tools: 'Ferramentas',
      remoteSensing: 'Sensoriamento Remoto',
      remoteSensingDescription: 'Especialista em análise de imagens de satélite, sistemas de Observação da Terra e processamento de dados geoespaciais para monitoramento ambiental.',
      gis: 'Sistemas de Informação Geográfica (SIG)',
      gisDescription: 'Proficiente em coleta, análise e visualização de dados espaciais usando ferramentas SIG avançadas para mapeamento e tomada de decisões.',
      dataAnalysis: 'Análise de Dados',
      dataAnalysisDescription: 'Habilidoso em análise estatística, modelagem de dados e interpretação de conjuntos de dados complexos para apoiar processos de pesquisa e tomada de decisões.',
      precisionAgriculture: 'Agricultura de Precisão',
      precisionAgricultureDescription: 'Especializado em validação de parâmetros biofísicos, monitoramento de culturas e gestão de recursos agrícolas usando dados de EO e tecnologia UAV.',
      dataManagement: 'Gestão de Dados',
      dataManagementDescription: 'Experiente em design de bancos de dados, validação de dados e desenvolvimento de modelos que geram insights acionáveis para gestão de recursos naturais.',
      mel: 'Monitoramento, Avaliação e Aprendizagem (MEL)',
      melDescription: 'Apaixonado por design de pesquisa, estruturas MEL e transformação de experiências de projeto em oportunidades de aprendizagem para melhoria contínua.',
      quantitativeQualitative: 'Investigação Quantitativa e Qualitativa',
      quantitativeQualitativeDescription: 'Habilidoso em projetar metodologias de pesquisa que combinam abordagens quantitativas e qualitativas para análise abrangente.',
      naturalResourcesManagement: 'Gestão de Recursos Naturais',
      naturalResourcesManagementDescription: 'Experiente em medir e analisar biodiversidade, monitoramento florestal e apoiar decisões de gestão sustentável de recursos naturais.',
      sustainableLivelihood: 'Meios de Subsistência Sustentáveis',
      sustainableLivelihoodDescription: 'Comprometido com o desenvolvimento de soluções que apoiem meios de subsistência sustentáveis e resiliência comunitária através de abordagens baseadas em dados.',
      communityEngagement: 'Engajamento Comunitário',
      communityEngagementDescription: 'Experiente em coleta participativa de dados espaciais e capacitação de comunidades na gestão de recursos naturais através de transferência de conhecimento.',
    },
    courses: {
      title: 'Cursos',
      coursesList: {
        bscAgriculturalEngineering: 'Licenciatura em Engenharia Agronómica',
        uavPrecisionAgriculture: 'UAV em Agricultura de Precisão',
        advancedStatistics: 'Estatística Avançada e Desenho Experimental',
        qualiQuantitativeResearch: 'Investigação Qualitativa e Quantitativa & Análise de Dados',
      },
      institutions: {
        eduardoMondlaneUniversity: 'Universidade Eduardo Mondlane',
        universityOfTwente: 'Universidade de Twente',
        centreOfExcellenceUEM: 'Centro de Excelência de Sistemas Agroalimentares e Nutrição da UEM',
        amazonasUniversity: 'Universidade do Amazonas',
      },
      locations: {
        mozambique: 'Moçambique',
        netherlands: 'Países Baixos',
        brazil: 'Brasil',
      },
    },
    publications: {
      title: 'Publicações',
      readMore: 'Ler Mais',
      publicationsList: {
        exposedUnmapped: 'Exposto mas não mapeado? Evidência de exposição diferencial a inundações em áreas urbanas carentes usando ciência cidadã',
        validationLeafArea: 'Validação do Índice de Área Foliar e Conteúdo de Água do Dossel através de imagens Sentinel-2 em culturas de milho (Zea Mays L.): Estudo de caso do distrito de Vilankulo',
      },
      authors: {
        oliveiraEtAl: 'Oliveira, L; Campomanes, E; Dijkstra, A; Belgiu, M; Adiku, P; Wanjiru, N; Lizian Onyango, L; Ibraimo, D; Flor, R; Van Den Bout, B; Zevenbergen, J & Kuffer, M',
        ibraimoMananze: 'Ibraimo, D.M. & Mananze, S.E.',
      },
      journals: {
        researchSquare: 'Research Square (Preprint)',
        scienceCribe: 'ScienceCribe',
      },
    },
    training: {
      title: 'Formação e Transferência de Competências',
      educationQuote: 'A educação é a arma mais poderosa que você pode usar para mudar o mundo',
      educationQuoteAuthor: 'Nelson Mandela',
      educationStatement: 'Movido pela citação acima, uso parte do meu tempo para partilhar e/ou transferir competências para os jovens e as gerações vindouras.',
      koboToolbox: {
        title: 'Kobo ToolBox para Recolha e Gestão de Dados',
        date: 'Novembro 2025',
        description: 'Esta formação foi fornecida a estudantes do último ano da Universidade Pungue pela Mozambique Flying Labs, como parte da nossa missão de transformação digital inclusiva no país. Os estudantes receberam material sobre princípios de investigação quantitativa, recolha de dados através de dispositivos móveis e gestão de dados. A formação de dois dias consistiu em componentes teóricos e práticos, permitindo que os estudantes melhorassem num contexto realista de campo de recolha de dados.',
        students: '25 estudantes',
        providedBy: 'Mozambique Flying Labs',
        programs: 'Programas abrangidos:',
        programsList: 'Ciências Biológicas, Agronomia, Engenharia de Energias Renováveis, Física e Matemática Aplicada',
        outcome: 'A formação enriqueceu as competências técnicas dos estudantes para melhorar a qualidade da sua investigação académica, bem como competências tecnológicas que os tornam competitivos no mercado de trabalho.',
      },
      googleEarthEngine: {
        title: 'Webinar Google Earth Engine',
        date: 'Agosto 2025',
        description: 'Neste webinar público organizado pela Mozambique Flying Labs, o nosso objetivo foi demonstrar na prática como os dados dos sistemas de observação da Terra podem ser usados para tomada de decisões informadas em vários setores através de conjuntos de dados disponíveis nesta poderosa plataforma de sensoriamento remoto.',
        attendees: '125 participantes',
        providedBy: 'Mozambique Flying Labs',
        examples: 'Exemplos práticos incluíram:',
        examplesList: 'Monitoramento agrícola, gestão de desastres e monitoramento de desflorestação.',
        participants: 'O webinar teve 125 pessoas presentes, incluindo estudantes, funcionários do setor público e privado, bem como representantes de ONGs e associações comunitárias.',
      },
      googleMyMaps: {
        title: 'Google My Maps para Mapeamento de Inundações',
        date: 'Fevereiro 2025',
        description: 'A formação Google My Maps para mapeamento de áreas inundadas fez parte do projeto Space4ALL, que visou capacitar membros de comunidades locais em bairros propensos a inundações nas cidades de Beira e Chimoio em Moçambique e Kisumu no Quénia. Esta formação visou capacitar os membros da comunidade para gerar e partilhar dados sobre inundações, bem como um histórico de locais críticos nos seus bairros, permitindo a receção de informações detalhadas sobre o histórico de inundações nestas áreas de intervenção do projeto Space4ALL e validando o modelo de alerta precoce de inundações.',
        providedBy: 'Universidade de Twente & Data4MOZ',
        locations: 'Localizações da formação:',
        locationsList: 'A formação foi oferecida por equipas da Faculdade de Ciências de Geoinformação da Universidade de Twente e Data4MOZ às comunidades de Nyalenda B e Manyata B no Quénia e 25 de Setembro, Centro Hípico, Munhava e Ponta-Gea em Moçambique.',
      },
      sustainableNRM: {
        title: 'Gestão Sustentável de Recursos Naturais',
        date: '2024',
        description: 'Esta formação foi fornecida a 5 comunidades da zona tampão do Parque Nacional da Gorongosa, como parte do projeto de gestão comunitária de recursos naturais através de dados espaciais participativos realizado pela Data4MOZ e financiado pela USAID.',
        communities: '5 comunidades',
        providedBy: 'Data4MOZ & USAID',
        communitiesList: 'Comunidades: Catemo, Nhabawa, Chidanga, Maciamboza e Muanandimae',
        outcomes: 'Esta formação permitiu sensibilizar os membros das comunidades de Catemo, Nhabawa, Chidanga, Maciamboza e Muanandimae sobre o uso sustentável dos recursos naturais e a identificação de meios de subsistência alternativos para aliviar a pressão sobre os recursos naturais, como apicultura, agricultura orgânica, etc., e para reduzir a caça furtiva e o corte ilegal de espécies madeireiras.',
      },
      communityGovernance: {
        title: 'Governança Comunitária',
        date: '2024',
        description: 'A formação em governança comunitária foi direcionada a 17 comités comunitários recém-estabelecidos pela Data4MOZ no Parque Nacional do Arquipélago de Bazaruto (BANP), com o objetivo de melhorar a participação e envolvimento comunitário quando se trata de estabelecer normas que impactam a vida das comunidades que residem no arquipélago.',
        committees: '17 comités',
        providedBy: 'Data4MOZ',
        contentTitle: 'Conteúdo da formação:',
        content: 'A formação consistiu em princípios de funcionamento para comités comunitários, sensibilização sobre conservação da biodiversidade aquática e terrestre, bem como o plano de gestão em vigor no BANP.',
      },
    },
    contact: {
      title: 'Entre em Contato',
      sendMessage: 'Enviar Mensagem',
      nome: 'Nome',
      nomePlaceholder: 'Digite seu nome',
      apelido: 'Apelido',
      apelidoPlaceholder: 'Digite seu apelido',
      email: 'Email',
      emailPlaceholder: 'seu.email@exemplo.com',
      assunto: 'Assunto',
      assuntoPlaceholder: 'Sobre o que é?',
      contacto: 'Contacto',
      contactoPlaceholder: '+258 845 486 656',
      mensagem: 'Mensagem',
      mensagemPlaceholder: 'Escreva sua mensagem aqui...',
      send: 'Enviar Mensagem',
      sending: 'Enviando...',
      success: 'Enviado!',
      successMessage: 'Mensagem enviada com sucesso! Entraremos em contato em breve.',
      errorMessage: 'Erro ao enviar mensagem. Por favor, tente novamente mais tarde.',
      connectWithUs: 'Conecte-se Conosco',
      scheduleConsultation: 'Agende uma consulta ou envie-nos uma mensagem',
      whatsappMessage: 'Olá! Gostaria de entrar em contato.',
      followUs: 'Siga-nos',
      location: 'Localização',
      country: 'Moçambique',
      province: 'Província de Manica',
      city: 'Chimoio',
    },
    footer: {
      allRightsReserved: 'Todos os direitos reservados',
    },
    chatbot: {
      openChatbot: 'Abrir chatbot',
      closeChatbot: 'Fechar chatbot',
      title: 'Pergunte sobre Deyril',
      online: 'Online',
      placeholder: 'Digite sua pergunta...',
      hint: 'Pergunte sobre experiência, competências, projetos, formação ou informações de contato',
      greeting: 'Olá! Estou aqui para responder perguntas sobre Deyril Marlon Ibraimo. O que gostaria de saber?',
      defaultResponse: 'Posso ajudá-lo a conhecer mais sobre a experiência, competências, projetos, formação, publicações e informações de contato de Deyril Marlon Ibraimo. O que gostaria de saber?',
      typing: 'Digitando...',
    },
    stats: {
      title: 'Conquistas & Impacto',
      yearsExperience: 'Anos de Experiência',
      projectsCompleted: 'Projetos Completados',
      publications: 'Publicações',
      communitiesTrained: 'Comunidades Capacitadas',
      countriesWorked: 'Países Trabalhados',
    },
    timeline: {
      title: 'Linha do Tempo Profissional',
      subtitle: 'Uma jornada através da minha experiência profissional, educação e conquistas principais',
      items: [
        {
          type: 'work',
          typeLabel: 'Experiência Profissional',
          title: 'Coordenador de Operações',
          period: 'Abr 2024 - Atual',
          organization: 'Data4MOZ, SA',
          location: 'Moçambique',
          description: 'Liderando operações e coordenando múltiplos projetos de pesquisa focados em avaliação de vulnerabilidade climática, monitoramento de uso da terra e engajamento comunitário em países africanos.',
          highlights: [
            'Mapeamento de vulnerabilidades climáticas de áreas carentes combinando ciência cidadã e tecnologia de observação da terra em Kisumu (Quênia), Beira e Chimoio (Moçambique) através do programa de pesquisa Space4ALL',
            'Monitoramento de mudanças no uso e cobertura da terra: identificação de áreas de pressão nos ecossistemas naturais',
            'Avaliação da sustentabilidade do uso da terra em práticas agrícolas no corredor de Beira',
            'Mapeamento de hotspots de crimes contra a vida selvagem na Zona Tampão do Parque Nacional de Gorongosa',
            'Realização de treinamento comunitário para rastreamento de crimes contra a vida selvagem usando ferramentas de Dados Espaciais',
            'Mapeamento de áreas agrícolas através de imagens Sentinel-2 e gestão de banco de dados de culturas',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Experiência Profissional',
          title: 'Coordenador de Operações',
          period: 'Atual',
          organization: 'Mozambique Flying Labs',
          location: 'Moçambique',
          description: 'Coordenando atividades de promoção STEM e desenvolvendo estratégias para adoção de tecnologia UAV, ciência de dados e inteligência artificial para desenvolvimento sustentável na África Austral.',
          highlights: [
            'Coordenação de atividades de promoção STEM (Ciência, Tecnologia, Engenharia e Matemática) em comunidades moçambicanas',
            'Desenvolvimento de estratégias para adoção de tecnologia de Veículos Aéreos Não Tripulados (UAV)',
            'Promoção de ciência de dados e inteligência artificial para desenvolvimento sustentável',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Experiência Profissional',
          title: 'Analista de Sensoriamento Remoto',
          period: '2023 - 2024',
          organization: 'Data4MOZ, SA',
          location: 'Moçambique',
          description: 'Realizando mapeamento participativo de recursos costeiros, mapeamento da cadeia de valor da pesca artesanal e desenvolvimento de estruturas de monitoramento baseadas em sensoriamento remoto para cobertura do solo e estimativa de biomassa.',
          highlights: [
            'Mapeamento participativo de recursos costeiros e Mapeamento da Cadeia de Valor da Pesca Artesanal na Área Chave de Biodiversidade do Grande Bazaruto (KBA)',
            'Desenvolvimento de estrutura de monitoramento HANPP baseada em sensoriamento remoto para tipos gerais de cobertura do solo (agrícola, floresta, pastagem, urbano)',
            'Estimativa de perdas de biomassa em países africanos: Moçambique, Senegal, Uganda e Etiópia através do projeto LUISA',
            'Monitoramento de culturas de Milho, Arroz e Soja com base em imagens de satélite na região central de Moçambique',
            'Identificação de parcelas agrícolas ineficientes',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Experiência Profissional',
          title: 'Formador em Entomologia Agrícola',
          period: 'Nov - Dez 2023',
          organization: 'Instituto Superior Dom Bosco',
          location: 'Moçambique',
          description: 'Realizando treinamento em manejo integrado de pragas agrícolas, identificação, monitoramento e treinamento de pragas agrícolas.',
          highlights: [
            'Realização de treinamento em manejo integrado de pragas agrícolas',
            'Identificação, monitoramento e treinamento de pragas agrícolas',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Experiência Profissional',
          title: 'Enumerador de Campo',
          period: 'Abr - Jun 2023',
          organization: 'Data4MOZ, SA',
          location: 'Moçambique',
          description: 'Liderando coleta de dados geoespaciais para pesquisas socioeconômicas, limpeza de dados e redação de relatórios, e gestão de equipe.',
          highlights: [
            'Liderança na coleta de dados geoespaciais para pesquisas socioeconômicas',
            'Limpeza de dados e redação de relatórios',
            'Gestão de equipe',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Experiência Profissional',
          title: 'Monitor de Tecnologia de Informação Geográfica',
          period: 'Jul - Dez 2022',
          organization: 'Instituto Superior Dom Bosco',
          location: 'Moçambique',
          description: 'Ensinando Tecnologia de Informação Geográfica e realizando avaliação de Investimento Baseado em Terra em Moçambique em parceria com SNV.',
          highlights: [
            'Ensino de Tecnologia de Informação Geográfica',
            'Avaliação de Investimento Baseado em Terra em Moçambique em parceria com SNV',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Experiência Profissional',
          title: 'Técnico de Campo em Programa de Pesquisa',
          period: 'Ago - Dez 2022',
          organization: 'Centro de Excelência em Sistemas Agroalimentares e Nutrição',
          location: 'Moçambique',
          description: 'Trabalhando em segurança alimentar, agronegócio e eficiência no uso de recursos na agricultura com base em sistema de Observação da Terra.',
          highlights: [
            'Coleta, processamento e desenvolvimento de insights baseados em sensoriamento remoto para tomada de decisão em agricultura sustentável',
            'Projeto: Segurança alimentar, agronegócio e eficiência no uso de recursos na agricultura com base em sistema de Observação da Terra',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Experiência Profissional',
          title: 'Assistente de Pesquisa',
          period: '2022',
          organization: 'Universidade Eduardo Mondlane',
          location: 'Moçambique',
          description: 'Aquisição e processamento de dados geoespaciais, sensoriamento remoto aplicado à agricultura de precisão.',
          highlights: [
            'Aquisição de dados geoespaciais (banco de dados Copernicus e USGS) e processamento de dados vetoriais',
            'Sensoriamento Remoto aplicado à agricultura de precisão - Mapeamento e monitoramento de áreas agrícolas com base em imagens Sentinel-2 usando SNAP',
          ],
        },
        {
          type: 'work',
          typeLabel: 'Experiência Profissional',
          title: 'Monitor de Genética e Melhoramento de Plantas',
          period: 'Set 2021 - Jun 2022',
          organization: 'Universidade Eduardo Mondlane',
          location: 'Moçambique',
          description: 'Supervisão de atividades de campo em melhoramento genético de plantas, melhoramento de plantas autógamas e alógamas, e biotecnologia de plantas.',
          highlights: [
            'Supervisão de atividades de campo em melhoramento genético de plantas',
            'Melhoramento de plantas autógamas e alógamas',
            'Biotecnologia de plantas',
          ],
        },
        {
          type: 'education',
          typeLabel: 'Educação',
          title: 'Licenciatura em Agronomia',
          period: '2019 - 2023',
          organization: 'Universidade Eduardo Mondlane (UEM)',
          location: 'Moçambique',
          description: 'Licenciatura em Agronomia com especialização em aplicações de sensoriamento remoto para agricultura e monitoramento de culturas.',
        },
        {
          type: 'education',
          typeLabel: 'Educação',
          title: 'Ensino Médio - Ciências e Biologia',
          period: '2014 - 2018',
          organization: 'Escola Secundária de Magude',
          location: 'Moçambique',
          description: 'Ensino médio com foco em Ciências e Biologia.',
        },
        {
          type: 'achievement',
          typeLabel: 'Certificado',
          title: 'UAVs em Agricultura de Precisão',
          period: '2024',
          organization: 'Faculdade de Geo-Informação e Observação da Terra da Universidade de Twente',
          location: 'Países Baixos',
          description: 'Certificado em aplicações de UAV para agricultura de precisão e sensoriamento remoto.',
        },
        {
          type: 'achievement',
          typeLabel: 'Certificado',
          title: 'Estatística Avançada e Desenho Experimental',
          period: '2023',
          organization: 'Universidade Eduardo Mondlane',
          location: 'Moçambique',
          description: 'Certificado em estatística avançada e desenho experimental para pesquisa agrícola.',
        },
        {
          type: 'achievement',
          typeLabel: 'Certificado',
          title: 'Pesquisa Qualitativa e Quantitativa e Análise de Dados',
          period: '2023',
          organization: 'Universidade Estadual do Amazonas',
          location: 'Brasil',
          description: 'Certificado em métodos de pesquisa qualitativa e quantitativa e análise de dados.',
        },
      ],
    },
    space4all: {
      title: 'SPACE4ALL',
      subtitle: 'Mapeamento de vulnerabilidades climáticas de favelas combinando ciência cidadã e tecnologia de observação da terra',
      period: '2024 - em curso',
      overview: 'Visão Geral',
      overviewText: 'SPACE4ALL é um projeto da ITC- University of Twente e NWO (Conselho Holandês de Pesquisa) que visa desvendar a vulnerabilidade climática de comunidades de favelas em grandes e cidades secundárias combinando métodos de Ciência Cidadã e Observação da Terra. Os métodos de Observação da Terra têm a vantagem de produzir dados físicos para grandes áreas e mostraram sua capacidade de mapear os aspectos físicos das favelas. O projeto aborda as lacunas desenvolvendo uma metodologia inovadora de IA combinando dados de Ciência Cidadã e dados de Observação da Terra com dados de mudanças climáticas para localizar pontos críticos de pobres urbanos expostos a perigos relacionados ao clima (por exemplo, aumento do nível do mar, tempestades, inundações, temperaturas extremas).',
      approach: 'Esta abordagem inovadora teve como principal objetivo o desenvolvimento e treinamento de modelos de aprendizado profundo para mapear o grau de vulnerabilidade das comunidades de favelas a riscos relacionados ao clima em grandes e cidades secundárias na África, para melhorar a precisão e a capacidade de alerta precoce de inundações do modelo.',
      locations: 'O projeto foi realizado em cidades africanas, nomeadamente Kisumu e Nairobi no Quênia, Accra e Tema em Gana e por último Beira e Chimoio em Moçambique, em parceria com instituições africanas como Data4MOZ e Sdi Kenya.',
      methodology: 'O estudo foi realizado em formato participativo onde os cidadãos puderam apontar e mapear as áreas vulneráveis da cidade a perigos climáticos, especialmente inundações, incluindo o nível de profundidade das inundações para os eventos mais recentes.',
      contribution: 'Contribuição',
      contributionText: 'Sob o guarda-chuva da Data4MOZ, como analista de sensoriamento remoto na instituição, meu papel para o Space4All foi desde a coleta de dados de campo e validação de modelos, conduzindo sessões de validação de campo em Kisumo (Quênia) junto com membros da ITC-University of Twente e liderando as atividades em Beira e Chimoio (Moçambique), envolvendo as comunidades locais e partes interessadas para sessões de validação de modelos e reunir subsídios por observações de campo, caminhadas de transecto e mapeamento de assentamentos informais.',
      institutions: 'Instituições envolvidas',
      furtherInfo: 'Para mais informações',
      contact: 'Lorraine Trento Oliveira (Pesquisadora ITC-UT Space4all)',
    },
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'pt')) {
      setLanguage(savedLanguage)
    }
  }, [])

  useEffect(() => {
    if (mounted) {
      localStorage.setItem('language', language)
    }
  }, [language, mounted])

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'pt' : 'en')
  }

  // Always provide the context, even during SSR
  // Use default language during SSR to avoid hydration mismatches
  const currentLanguage = mounted ? language : 'en'
  const currentTranslations = translations[currentLanguage] as Translations

  return (
    <LanguageContext.Provider value={{ language: currentLanguage, t: currentTranslations, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

